# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6973a4458836889fa550c80781aa6d847f545050e45a11d6e2f7c9c614cd33ab23f704e453d781f37fcbc656e202df8a4167846254069ceefc4e76209a5ccb74

test:
  secret_key_base: 653f70f7670efff9a9497710a15edffbca711bd5375f8718ad52e8c06476c4300c36eadf5f42b632527a2aa3ac24a5e10c770b9ca48c520ea3812674d599fc45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
